[2023-11-23T23:13:52.069+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airbyte_example_airflow_dag.check_if_file_exists_task manual__2023-11-23T23:12:44.624946+00:00 [queued]>
[2023-11-23T23:13:52.079+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airbyte_example_airflow_dag.check_if_file_exists_task manual__2023-11-23T23:12:44.624946+00:00 [queued]>
[2023-11-23T23:13:52.080+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-23T23:13:52.119+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): check_if_file_exists_task> on 2023-11-23 23:12:44.624946+00:00
[2023-11-23T23:13:52.125+0000] {standard_task_runner.py:57} INFO - Started process 1061 to run task
[2023-11-23T23:13:52.127+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'airbyte_example_***_dag', 'check_if_file_exists_task', 'manual__2023-11-23T23:12:44.624946+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/example.py', '--cfg-path', '/tmp/tmponbiyjmv']
[2023-11-23T23:13:52.128+0000] {standard_task_runner.py:85} INFO - Job 67: Subtask check_if_file_exists_task
[2023-11-23T23:13:52.191+0000] {task_command.py:416} INFO - Running <TaskInstance: airbyte_example_airflow_dag.check_if_file_exists_task manual__2023-11-23T23:12:44.624946+00:00 [running]> on host 471f0a6f2fee
[2023-11-23T23:13:52.316+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='airbyte_example_***_dag' AIRFLOW_CTX_TASK_ID='check_if_file_exists_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-23T23:12:44.624946+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-23T23:12:44.624946+00:00'
[2023-11-23T23:13:52.323+0000] {base.py:73} INFO - Using connection ID '***-file-connector' for task execution.
[2023-11-23T23:13:52.323+0000] {filesystem.py:64} INFO - Poking for file /tmp/airbyte_local/json_from_faker/_airbyte_raw_products.jsonl
[2023-11-23T23:14:52.392+0000] {base.py:73} INFO - Using connection ID '***-file-connector' for task execution.
[2023-11-23T23:14:52.393+0000] {filesystem.py:64} INFO - Poking for file /tmp/airbyte_local/json_from_faker/_airbyte_raw_products.jsonl
[2023-11-23T23:14:52.393+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 274, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 60.07703873100036 seconds exceeds the specified timeout of 5.0.
[2023-11-23T23:14:52.428+0000] {taskinstance.py:1400} INFO - Immediate failure requested. Marking task as FAILED. dag_id=airbyte_example_***_dag, task_id=check_if_file_exists_task, execution_date=20231123T231244, start_date=20231123T231352, end_date=20231123T231452
[2023-11-23T23:14:52.476+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 67 for task check_if_file_exists_task (Sensor has timed out; run duration of 60.07703873100036 seconds exceeds the specified timeout of 5.0.; 1061)
[2023-11-23T23:14:52.520+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-23T23:14:52.539+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
