[2023-11-26T19:55:45.635+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airbyte_example_airflow_dag.check_if_file_exists_task manual__2023-11-26T19:54:38.379208+00:00 [queued]>
[2023-11-26T19:55:45.643+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airbyte_example_airflow_dag.check_if_file_exists_task manual__2023-11-26T19:54:38.379208+00:00 [queued]>
[2023-11-26T19:55:45.643+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-26T19:55:45.681+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): check_if_file_exists_task> on 2023-11-26 19:54:38.379208+00:00
[2023-11-26T19:55:45.688+0000] {standard_task_runner.py:57} INFO - Started process 381 to run task
[2023-11-26T19:55:45.691+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'airbyte_example_***_dag', 'check_if_file_exists_task', 'manual__2023-11-26T19:54:38.379208+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/example.py', '--cfg-path', '/tmp/tmp1dzr4hnt']
[2023-11-26T19:55:45.692+0000] {standard_task_runner.py:85} INFO - Job 86: Subtask check_if_file_exists_task
[2023-11-26T19:55:45.763+0000] {task_command.py:416} INFO - Running <TaskInstance: airbyte_example_airflow_dag.check_if_file_exists_task manual__2023-11-26T19:54:38.379208+00:00 [running]> on host 471f0a6f2fee
[2023-11-26T19:55:45.911+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='airbyte_example_***_dag' AIRFLOW_CTX_TASK_ID='check_if_file_exists_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-26T19:54:38.379208+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-26T19:54:38.379208+00:00'
[2023-11-26T19:55:45.917+0000] {base.py:73} INFO - Using connection ID '***-file-connector' for task execution.
[2023-11-26T19:55:45.917+0000] {filesystem.py:64} INFO - Poking for file /tmp/airbyte_local/json_from_faker/_airbyte_raw_products.jsonl
[2023-11-26T19:56:45.987+0000] {base.py:73} INFO - Using connection ID '***-file-connector' for task execution.
[2023-11-26T19:56:45.987+0000] {filesystem.py:64} INFO - Poking for file /tmp/airbyte_local/json_from_faker/_airbyte_raw_products.jsonl
[2023-11-26T19:56:45.988+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 274, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 60.07666359799987 seconds exceeds the specified timeout of 5.0.
[2023-11-26T19:56:46.041+0000] {taskinstance.py:1400} INFO - Immediate failure requested. Marking task as FAILED. dag_id=airbyte_example_***_dag, task_id=check_if_file_exists_task, execution_date=20231126T195438, start_date=20231126T195545, end_date=20231126T195646
[2023-11-26T19:56:46.089+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 86 for task check_if_file_exists_task (Sensor has timed out; run duration of 60.07666359799987 seconds exceeds the specified timeout of 5.0.; 381)
[2023-11-26T19:56:46.137+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-26T19:56:46.166+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
