[2023-11-27T12:13:32.011+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airbyte_example_airflow_dag.check_if_file_exists_task manual__2023-11-27T12:12:25.615589+00:00 [queued]>
[2023-11-27T12:13:32.018+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airbyte_example_airflow_dag.check_if_file_exists_task manual__2023-11-27T12:12:25.615589+00:00 [queued]>
[2023-11-27T12:13:32.018+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-27T12:13:32.054+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): check_if_file_exists_task> on 2023-11-27 12:12:25.615589+00:00
[2023-11-27T12:13:32.062+0000] {standard_task_runner.py:57} INFO - Started process 2286 to run task
[2023-11-27T12:13:32.065+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'airbyte_example_***_dag', 'check_if_file_exists_task', 'manual__2023-11-27T12:12:25.615589+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/example.py', '--cfg-path', '/tmp/tmpee5sfwo7']
[2023-11-27T12:13:32.066+0000] {standard_task_runner.py:85} INFO - Job 102: Subtask check_if_file_exists_task
[2023-11-27T12:13:32.133+0000] {task_command.py:416} INFO - Running <TaskInstance: airbyte_example_airflow_dag.check_if_file_exists_task manual__2023-11-27T12:12:25.615589+00:00 [running]> on host 471f0a6f2fee
[2023-11-27T12:13:32.280+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='airbyte_example_***_dag' AIRFLOW_CTX_TASK_ID='check_if_file_exists_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-27T12:12:25.615589+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-27T12:12:25.615589+00:00'
[2023-11-27T12:13:32.290+0000] {base.py:73} INFO - Using connection ID '***-file-connector' for task execution.
[2023-11-27T12:13:32.291+0000] {filesystem.py:64} INFO - Poking for file /tmp/airbyte_local/json_from_faker/_airbyte_raw_products.jsonl
[2023-11-27T12:14:32.364+0000] {base.py:73} INFO - Using connection ID '***-file-connector' for task execution.
[2023-11-27T12:14:32.367+0000] {filesystem.py:64} INFO - Poking for file /tmp/airbyte_local/json_from_faker/_airbyte_raw_products.jsonl
[2023-11-27T12:14:32.367+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 274, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 60.08589028000097 seconds exceeds the specified timeout of 5.0.
[2023-11-27T12:14:32.375+0000] {taskinstance.py:1400} INFO - Immediate failure requested. Marking task as FAILED. dag_id=airbyte_example_***_dag, task_id=check_if_file_exists_task, execution_date=20231127T121225, start_date=20231127T121332, end_date=20231127T121432
[2023-11-27T12:14:32.439+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 102 for task check_if_file_exists_task (Sensor has timed out; run duration of 60.08589028000097 seconds exceeds the specified timeout of 5.0.; 2286)
[2023-11-27T12:14:32.474+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-27T12:14:32.503+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
